SELECT *
FROM public."Store_AITI"
LIMIT 10;

-- NUMBER OF TRANSACTIONS
SELECT COUNT(invoice_no)
FROM public."Store_AITI";

-- NUMBER OF TRANSACTIONS WITH QUANTITY GREATER THAN 3
SELECT COUNT(invoice_no)
FROM public."Store_AITI"
WHERE "Quantity" > 3;

-- TOTAL NUMBER OF QUANTITY SOLD ACROSS TRANSACTIONS
SELECT SUM("Quantity")
FROM public."Store_AITI";

-- TOTAL NUMBER OF SHOES SOLD
SELECT SUM("Quantity")
FROM public."Store_AITI"
WHERE "Category" = 'Shoes';

-- CUSTOMERS WITH BLANK CUSTOMER ID
SELECT COUNT(invoice_no)
FROM public."Store_AITI"
WHERE "Customer_id" = ''
OR "Customer_id" = ' ';

-- TRANSACTIONS WITH REVENUE GREATER THAN $5,000 WITH NON CREDIT CARD PAYMENT METHOD
SELECT invoice_no, "Category", "Quantity", "Revenue", "Payment_method", "Shopping_Mall"
FROM public."Store_AITI"
WHERE "Revenue" > 5000
AND "Payment_method" <> 'Credit Card';

-- FOREM INSTABUL CUSTOMERS > 30
SELECT "Age" AS TARGET, "Revenue"
FROM public."Store_AITI"
WHERE "Age" > 30
AND "Shopping_Mall" = 'Forum Istanbul';

-- REVENUE GENERATED BY KANYON MALL
SELECT SUM("Revenue") AS Kanyon_Revenue
FROM public."Store_AITI"
WHERE "Shopping_Mall" = 'Kanyon';

SELECT SUM("Revenue") AS Total_Revenue
FROM public."Store_AITI";


-- PERCENTAGE CONTRIBUTION OF KANYON MALL
SELECT((Kanyon_Revenue/Total_Revenue) * 100) AS Percentage_Kanyon
FROM (
    SELECT
        SUM("Revenue") FILTER ( WHERE "Shopping_Mall" = 'Kanyon') AS Kanyon_Revenue,
        SUM("Revenue") AS Total_Revenue
	FROM public."Store_AITI"
);

-- SHOES TRANSACTIONS WITH REVENUE GREATER THAN $3000
SELECT invoice_no, "Revenue"
FROM public."Store_AITI"
WHERE "Category" = 'Shoes'
AND "Revenue" > 3000;

-- TOTAL SALES OF CLOTHING ACROSS THE YEARS
SELECT
    DATE_TRUNC('year', "Date") AS YEAR,
	SUM("Revenue") AS Total_Sales
FROM public."Store_AITI"
WHERE "Category" = 'Clothing'
GROUP BY YEAR
ORDER BY YEAR;


-- EXTRACTING CUSTOMER ID
SELECT
    "Customer_id", 
	RIGHT("Customer_id", 4) AS Unique_Identifier
FROM public."Store_AITI";


-- REMOVING XTRA SPACES FROM THE SHOPPING MALL NAMES
SELECT "Shopping_Mall", TRIM("Shopping_Mall") AS Cleaned_shopping_mall
FROM public."Store_AITI";


-- COUNTING THE NUMBER OF CHARACTER EACH CUSTOMER ID HAS
SELECT "Customer_id", LENGTH("Customer_id")
FROM public."Store_AITI";


-- TRANSACTIONS THAT OCCURED ON WEEKENDS
SELECT COUNT(*) AS weekend_transactions_count
FROM public."Store_AITI"
WHERE EXTRACT(DOW FROM "Date") IN (0,6);



-- REVENUE FOR EACH DISTINCT CUSTOMER ID
SELECT
    "Customer_id",
	SUM("Revenue") AS Total_Revenue
FROM public."Store_AITI"
GROUP BY
    "Customer_id"
ORDER BY
    Total_Revenue DESC;


-- TOP 5 CUSTOMERS
SELECT
    "Customer_id",
	SUM("Revenue") AS Total_Revenue,
	SUM("Quantity") AS Total_Quantity,
	ROUND(SUM("Revenue")/SUM("Quantity"),2) AS Average_revenue_per_transaction
FROM public."Store_AITI"
GROUP BY
    "Customer_id"
ORDER BY
    SUM("Revenue")/SUM("Quantity") DESC
LIMIT 5;